export const usersTypes = {
	REGISTER_USER: "REGISTER_USER",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT_USER: "LOGOUT_USER",
	UNAUTHORIZED: "UNAUTHORIZED",
};

export const briefsTypes = {
	FETCH_BRIEFS: "FETCH_BRIEFS",
	FETCH_BRIEF: "FETCH_BRIEF",
	CREATE_BRIEF: "CREATE_BRIEF",
	EDIT_BRIEF: "EDIT_BRIEF",
	DELETE_BRIEF: "DELETE_BRIEF",
};
