export const usersTypes = {
	REGISTER_USER: "REGISTER_USER",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT_USER: "LOGOUT_USER",
	UNAUTHORIZED: "UNAUTHORIZED",
};

export const briefsTypes = {
	FETCH_BRIEFS: "FETCH_BRIEFS",
	CREATE_BRIEF: "CREATE_BRIEF",
};
