export const usersTypes = {
	REGISTER_USER: "REGISTER_USER",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT_USER: "LOGOUT_USER",
	UNAUTHORIZED: "UNAUTHORIZED",
	ADD_TOKENS: "ADD_TOKENS",
};

export const briefsTypes = {
	FETCH_BRIEFS: "FETCH_BRIEFS",
	FETCH_BRIEF: "FETCH_BRIEF",
	CREATE_BRIEF: "CREATE_BRIEF",
	EDIT_BRIEF: "EDIT_BRIEF",
	DELETE_BRIEF: "DELETE_BRIEF",
};

export const applicationsTypes = {
	FETCH_APPLICATIONS: "FETCH_APPLICATIONS",
	FETCH_APPLICATION: "FETCH_APPLICATION",
	CREATE_APPLICATION: "CREATE_APPLICATION",
	EDIT_APPLICATION: "EDIT_APPLICATION",
	DELETE_APPLICATION: "DELETE_APPLICATION",
};
