const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const briefSchema = new mongoose.Schema(
	{
		title: String,
		description: String,
		dueDate: Date,
		budget: Number,
		currency: {
			type: String,
			enum: ["USD", "CAD", "EUR", "GBP"],
		},

		logo: String,
		author: {
			type: Schema.Types.ObjectId,
			ref: "User",
		},
		numberOfApplicationsWanted: { type: Number, default: 500 },
		numberOfApplicationsSubmitted: { type: Number, default: 0 },
		media: {
			type: String,
			enum: [
				"Film",
				"Web",
				"TV",
				"Advertising",
				"Video Game",
				"Trailer",
				"Radio",
				"Podcast",
				"Corporate",
				"Other",
				"All Media",
			],
		},
		use: [
			{
				type: String,
				enum: ["Soundtrack", "Background Music", "Credits"],
			},
		],
		licenseDuration: {
			type: String,
			enum: [
				"1 week",
				"2 weeks",
				"1 month",
				"2 months",
				"3 months",
				"6 months",
				"9 months",
				"1 year",
				"2 years",
				"3 years",
				"5 years",
				"10 years",
				"Perpetuity",
			],
		},
		extractDuration: Number,
		territory: [
			{
				type: String,
				enum: [
					"Europe",
					"USA and Canada", // deprecated
					"Canada",
					"USA",
					"Africa",
					"South America",
					"Asia",
					"Australia and New Zealand",
					"Worldwide",
				],
			},
		],
		genres: [
			{
				type: String,
				enum: [
					"Pop",
					"Electronic",
					"Rock",
					"Indie",
					"Hip Hop",
					"Funk & Soul",
					"Folk",
					"Classical",
					"World",
					"Jazz",
					"Country",
					"Blues",
					"Experimental",
					"Reggae",
					"Children's music",
				],
			},
		],
		vocals: [
			{
				type: String,
				enum: ["Instrumental Only", "Female", "Male", "Rap", "Choir", "Kids"],
			},
		],
		moods: [
			{
				type: String,
				enum: [
					"Happy",
					"Epic",
					"Dreamy",
					"Euphoric",
					"Laid Back",
					"Running",
					"Relaxing",
					"Suspense",
					"Mysterious",
					"Sentimental",
					"Sad",
				],
			},
		],
		instruments: [
			{
				type: String,
				enum: [
					"Piano",
					"Flute",
					"Veena",
					"Drums",
					"Mridangam",
					"Violin Guitar",
					"Triangle",
					"Trumpet",
					"Saxophone",
					"Mouth organ",
					"Cello",
					"Xylophone",
					"Clap box",
					"Electric guitar",
					"Bass",
					"Bugle",
					"Harpe",
					"Harmonium",
					"Oboe",
					"Maracas",
					"Cymbal",
					"Accordion",
					"Bongo",
					"Bell",
					"Horn",
					"Banjo",
					"Conga",
					"Keyboard",
					"Gong",
					"Pipe organ",
					"Comet",
					"Tambourine",
					"Clarinet",
					"Harmonica",
					"Tuba",
					"Bass drum",
					"snare drum",
					"Euphorium",
					"Piccolo",
					"Lute",
					"Marimba",
					"Bassoon",
					"Cornet",
					"Celesta",
					"Spinet",
					"Oud",
					"Yueqin",
					"Dholak",
					"Tabla",
					"Damru",
					"Ssrangi",
					"Sitar",
					"Gu-zheng",
					"Ektara",
					"Shehnai",
					"Sarod",
					"Pungi",
					"Gramophone",
					"Tubular Chimes",
				],
			},
		],
		tempo: {
			type: String,
			enum: [
				"Very slow (40-60 bpm)",
				"Slow (60-75 bpm)",
				"Medium (75-110)",
				"Fast (110-150)",
				"Very fast (150-200)",
			],
		},
		exclusivity: Boolean,
		open: { type: Boolean, default: true },
		private: { type: Boolean, default: false },
		references: [
			{
				link: String,
				title: String,
				comment: String,
			},
		],
	},
	{
		timestamps: true,
		collection: "briefs",
	}
);

const Brief = mongoose.model("Brief", briefSchema);
module.exports = Brief;
